// Generated by work/promo/build-audio.py + emit-timeline.py. Do not edit by hand:
// these are the MEASURED narration cues, and every scene is cut against them.
// Rebuild with: python3 build-audio.py && python3 emit-timeline.py

export const TOTAL = 89.92999999999998;
export const TURN = {"fade_from": 58.3, "silent_from": 60.3, "silent_to": 62.6, "back_by": 64.1} as const;

/** start/end of each narration line, in seconds. */
export const VO = {
  "01": { start: 1.0, end: 5.88, note: "1968 \u2014 rummage sale" },
  "02": { start: 6.23, end: 11.52, note: "the sum + naira card" },
  "03": { start: 11.92, end: 18.28, note: "one terminal, whole school" },
  "04": { start: 18.73, end: 20.96, note: "one of the boys was thirteen" },
  "05": { start: 21.81, end: 23.39, note: "THE REVEAL \u2014 hold before the name" },
  "06": { start: 24.19, end: 26.56, note: "not a genius yet" },
  "08": { start: 27.16, end: 30.46, note: "the gap was never talent" },
  "09": { start: 31.36, end: 39.85, note: "ARC opens \u2014 Lagos, age 10" },
  "10": { start: 40.2, end: 43.92, note: "he isn't behind" },
  "11": { start: 44.27, end: 48.08, note: "3 years \u2014 age 13" },
  "12": { start: 48.38, end: 52.83, note: "6 years \u2014 age 16" },
  "13": { start: 53.13, end: 57.5, note: "13 years \u2014 the whiteboard" },
  "14": { start: 58.3, end: 60.11, note: "none of that has happened yet" },
  "15": { start: 61.41, end: 62.62, note: "THE TURN \u2014 music out, cut to real" },
  "16": { start: 63.17, end: 70.18, note: "real Python, four belts" },
  "17": { start: 70.58, end: 76.71, note: "ages, Saturdays, Eekoyi" },
  "18": { start: 77.36, end: 81.4, note: "callback to 1968" },
  "19": { start: 81.75, end: 84.12, note: "children should be early" },
  "20": { start: 84.57, end: 88.33, note: "end card" },
} as const;
